{den, ...}: {
  den.aspects.barbara-bar = {
    OS,
    host,
    ...
  }: {
    nixos = {
      pkgs,
      lib,
      config,
      ...
    }: {
      # Auto-generated by compose2nix.
      # Runtime
      virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
      };

      # Enable container name DNS for all Podman networks.
      networking.firewall.interfaces = let
        matchAll =
          if !config.networking.nftables.enable
          then "podman+"
          else "podman*";
      in {
        "${matchAll}".allowedUDPPorts = [53];
      };

      virtualisation.oci-containers.backend = "podman";

      # Containers
      virtualisation.oci-containers.containers."scanity-broker" = {
        image = "docker.io/library/redis:8";
        environment = {"TZ" = "Europe/Berlin";};
        volumes = ["scanity_redisdata:/data:rw"];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=broker"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-broker" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_redisdata.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_redisdata.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-broker-vanilla" = {
        image = "docker.io/library/redis:8";
        environment = {
          "TZ" = "Europe/Berlin";
        };
        volumes = [
          "scanity_redisdata-vanilla:/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=broker-vanilla"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-broker-vanilla" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_redisdata-vanilla.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_redisdata-vanilla.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-db" = {
        image = "docker.io/library/postgres:17";
        environment = {
          "POSTGRES_DB" = "paperless";
          "POSTGRES_PASSWORD" = "paperless";
          "POSTGRES_USER" = "paperless";
          "TZ" = "Europe/Berlin";
        };
        volumes = [
          "scanity_pgdata:/var/lib/postgresql/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=db"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-db" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_pgdata.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_pgdata.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-db-vanilla" = {
        image = "docker.io/library/postgres:17";
        environment = {
          "POSTGRES_DB" = "paperless";
          "POSTGRES_PASSWORD" = "paperless";
          "POSTGRES_USER" = "paperless";
          "TZ" = "Europe/Berlin";
        };
        volumes = [
          "scanity_pgdata-vanilla:/var/lib/postgresql/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=db-vanilla"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-db-vanilla" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_pgdata-vanilla.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
          "podman-volume-scanity_pgdata-vanilla.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-gotenberg" = {
        image = "docker.io/gotenberg/gotenberg:8.22";
        environment = {
          "TZ" = "Europe/Berlin";
        };
        cmd = ["gotenberg" "--chromium-disable-javascript=true" "--chromium-allow-list=file:///tmp/.*"];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=gotenberg"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-gotenberg" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-gotenberg-vanilla" = {
        image = "docker.io/gotenberg/gotenberg:8.22";
        environment = {
          "TZ" = "Europe/Berlin";
        };
        cmd = ["gotenberg" "--chromium-disable-javascript=true" "--chromium-allow-list=file:///tmp/.*"];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=gotenberg-vanilla"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-gotenberg-vanilla" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-paperless-gpt" = {
        image = "paperless-dbr";
        environment = {
          "AUTO_GENERATE_CORRESPONDENTS" = "true";
          "AUTO_GENERATE_CREATED_DATE" = "true";
          "AUTO_GENERATE_CUSTOM_FIELD" = "true";
          "AUTO_GENERATE_TAGS" = "true";
          "AUTO_GENERATE_TITLE" = "true";
          "AUTO_OCR_TAG" = "paperless-gpt-ocr-auto";
          "AUTO_TAG" = "paperless-gpt-auto";
          "CORRESPONDENT_BLACK_LIST" = "Daniel Bruder, Herr Bruder, Dr. Daniel Bruder, Daniel Milan Bruder";
          "CREATE_LOCAL_HOCR" = "true";
          "CREATE_LOCAL_PDF" = "true";
          "LLM_LANGUAGE" = "German";
          "LLM_MODEL" = "qwen3:8b";
          "LLM_PROVIDER" = "ollama";
          "LOCAL_HOCR_PATH" = "/app/hocr";
          "LOCAL_PDF_PATH" = "/app/pdf";
          "LOG_LEVEL" = "debug";
          "MANUAL_TAG" = "paperless-gpt";
          "OCR_LIMIT_PAGES" = "8";
          "OCR_PROCESS_MODE" = "image";
          "OCR_PROVIDER" = "llm";
          "OLLAMA_HOST" = "http://host.docker.internal:11434";
          "PAPERLESS_API_TOKEN" = "c76137bf98f9e9013563acebb1138c2b39db7032";
          "PAPERLESS_BASE_URL" = "http://host.docker.internal:8000";
          "PAPERLESS_CUSTOM_FIELD_WRITING_MODE" = "update";
          "PDF_COPY_METADATA" = "true";
          "PDF_OCR_COMPLETE_TAG" = "paperless-gpt-ocr-complete";
          "PDF_OCR_TAGGING" = "true";
          "PDF_REPLACE" = "true";
          "PDF_SKIP_EXISTING_OCR" = "false";
          "PDF_UPLOAD" = "true";
          "TOKEN_LIMIT" = "4096";
          "TZ" = "Europe/Berlin";
          "VISION_LLM_MODEL" = "nanonets-ocr";
          "VISION_LLM_PROVIDER" = "ollama";
        };
        volumes = [
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/data/paperless-gpt/hocr:/app/hocr:rw"
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/data/paperless-gpt/pdf:/app/pdf:rw"
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/data/paperless-gpt/prompts:/app/prompts:rw"
        ];
        ports = [
          "8080:8080/tcp"
        ];
        log-driver = "journald";
        extraOptions = [
          "--add-host=host.docker.internal:host-gateway"
          "--network-alias=paperless-gpt"
          "--network=bridge"
        ];
      };
      systemd.services."podman-scanity-paperless-gpt" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "no";
        };
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-paperless-vanilla" = {
        image = "ghcr.io/paperless-ngx/paperless-ngx:latest";
        environment = {
          "PAPERLESS_APP_TITLE" = "scanity";
          "PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX" = "ASN";
          "PAPERLESS_CONSUMER_BARCODE_RETAIN_SPLIT_PAGES" = "true";
          "PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT" = "true";
          "PAPERLESS_CONSUMER_BARCODE_UPSCALE" = "2.5";
          "PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE" = "true";
          "PAPERLESS_CONSUMER_ENABLE_BARCODES" = "true";
          "PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED" = "true";
          "PAPERLESS_CONSUMER_POLLING" = "5";
          "PAPERLESS_CONSUMER_RECURSIVE" = "true";
          "PAPERLESS_DBHOST" = "db";
          "PAPERLESS_DEBUG" = "true";
          "PAPERLESS_OCR_CLEAN" = "clean-final";
          "PAPERLESS_OCR_DESKEW" = "true";
          "PAPERLESS_OCR_LANGUAGE" = "deu+eng";
          "PAPERLESS_OCR_ROTATE_PAGES" = "true";
          "PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD" = "9";
          "PAPERLESS_REDIS" = "redis://broker:6379";
          "PAPERLESS_TASK_WORKERS" = "4";
          "PAPERLESS_TIKA_ENABLED" = "1";
          "PAPERLESS_TIKA_ENDPOINT" = "http://tika:9998";
          "PAPERLESS_TIKA_GOTENBERG_ENDPOINT" = "http://gotenberg:3000";
          "PAPERLESS_TIME_ZONE" = "Europe/Berlin";
          "TZ" = "Europe/Berlin";
          "USERMAP_GID" = "20";
          "USERMAP_UID" = "502";
        };
        volumes = [
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/consume-vanilla:/usr/src/paperless/consume:rw"
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/data/paperless-vanilla/data:/usr/src/paperless/data:rw"
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/data/paperless-vanilla/export:/usr/src/paperless/export:rw"
          "/home/dbr/src/nix/fleet/document-pipeline/paperless-web/data/paperless-vanilla/media:/usr/src/paperless/media:rw"
        ];
        ports = [
          "8001:8000/tcp"
        ];
        dependsOn = [
          "scanity-broker-vanilla"
          "scanity-db-vanilla"
          "scanity-gotenberg-vanilla"
          "scanity-tika-vanilla"
        ];
        log-driver = "journald";
        extraOptions = [
          "--health-cmd=[\"curl\", \"-H\", \"Token b9e51317a6ad461a603a463ce5228e5c40d50cdb\", \"http://localhost:8001/api/documents\"]"
          "--health-interval=7s"
          "--health-retries=5"
          "--health-start-period=7s"
          "--health-timeout=7s"
          "--network-alias=paperless-vanilla"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-paperless-vanilla" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-tika" = {
        image = "docker.io/apache/tika:latest";
        environment = {
          "TZ" = "Europe/Berlin";
        };
        log-driver = "journald";
        extraOptions = [
          "--network-alias=tika"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-tika" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };
      virtualisation.oci-containers.containers."scanity-tika-vanilla" = {
        image = "docker.io/apache/tika:latest";
        environment = {
          "TZ" = "Europe/Berlin";
        };
        log-driver = "journald";
        extraOptions = [
          "--network-alias=tika-vanilla"
          "--network=scanity_default"
        ];
      };
      systemd.services."podman-scanity-tika-vanilla" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-scanity_default.service"
        ];
        requires = [
          "podman-network-scanity_default.service"
        ];
        partOf = [
          "podman-compose-scanity-root.target"
        ];
        wantedBy = [
          "podman-compose-scanity-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-scanity_default" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f scanity_default";
        };
        script = ''
          podman network inspect scanity_default || podman network create scanity_default
        '';
        partOf = ["podman-compose-scanity-root.target"];
        wantedBy = ["podman-compose-scanity-root.target"];
      };

      # Volumes
      systemd.services."podman-volume-scanity_pgdata" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect scanity_pgdata || podman volume create scanity_pgdata
        '';
        partOf = ["podman-compose-scanity-root.target"];
        wantedBy = ["podman-compose-scanity-root.target"];
      };
      systemd.services."podman-volume-scanity_pgdata-vanilla" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect scanity_pgdata-vanilla || podman volume create scanity_pgdata-vanilla
        '';
        partOf = ["podman-compose-scanity-root.target"];
        wantedBy = ["podman-compose-scanity-root.target"];
      };
      systemd.services."podman-volume-scanity_redisdata" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect scanity_redisdata || podman volume create scanity_redisdata
        '';
        partOf = ["podman-compose-scanity-root.target"];
        wantedBy = ["podman-compose-scanity-root.target"];
      };
      systemd.services."podman-volume-scanity_redisdata-vanilla" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect scanity_redisdata-vanilla || podman volume create scanity_redisdata-vanilla
        '';
        partOf = ["podman-compose-scanity-root.target"];
        wantedBy = ["podman-compose-scanity-root.target"];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-scanity-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = ["multi-user.target"];
      };
    };
  };
}
